import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';
import { environment } from 'src/environments/environment';

@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class IconsModule { 

  constructor (
    iconRegistry: MatIconRegistry,
    sanitizer: DomSanitizer,
  ) {
    iconRegistry.addSvgIcon(
      'vertical-menu',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/vertical_menu.svg`)
    );
    iconRegistry.addSvgIcon(
      'menu',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/menu.svg`)
    );
    iconRegistry.addSvgIcon(
      'download',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/download.svg`)
    );
    iconRegistry.addSvgIcon(
      'reload',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/reload.svg`)
    );
    iconRegistry.addSvgIcon(
      'attachment',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/attachment.svg`)
    );
    iconRegistry.addSvgIcon(
      'save',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/save.svg`)
    );
    iconRegistry.addSvgIcon(
      'cancel',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/cancel.svg`)
    );
    iconRegistry.addSvgIcon(
      'checklist',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/checklist.svg`)
    );
    iconRegistry.addSvgIcon(
      'support',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/support.svg`)
    );
    iconRegistry.addSvgIcon(
      'checklist-header',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/checklist_header.svg`)
    );
    iconRegistry.addSvgIcon(
      'small-locked',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/small_locked.svg`)
    );
    iconRegistry.addSvgIcon(
      'arrow-up',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/arrow_up.svg`)
    );
    iconRegistry.addSvgIcon(
      'arrow-down',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/arrow_down.svg`)
    );
    iconRegistry.addSvgIcon(
      'check',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/check.svg`)
    );
    iconRegistry.addSvgIcon(
      'warn-line',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/warn_line.svg`)
    );  
    iconRegistry.addSvgIcon(
      'warn-fill',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/warn_fill.svg`)
    );
    iconRegistry.addSvgIcon(
      'block',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/block.svg`)
    );
    iconRegistry.addSvgIcon(
      'attachment-file',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/attachment_file.svg`)
    );
    iconRegistry.addSvgIcon(
      'more_info',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/more_info.svg`)
    );
    iconRegistry.addSvgIcon(
      'event',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/event.svg`)
    );
    iconRegistry.addSvgIcon(
      'man',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/man.svg`)
    );
    iconRegistry.addSvgIcon(
      'briefcase',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/briefcase.svg`)
    );
    iconRegistry.addSvgIcon(
      'gear',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/gear.svg`)
    );
    iconRegistry.addSvgIcon(
      'industry',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/industry.svg`)
    );
    iconRegistry.addSvgIcon(
      'country',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/country.svg`)
    );
    iconRegistry.addSvgIcon(
      'company',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/company.svg`)
    );
    iconRegistry.addSvgIcon(
      'priority',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/priority.svg`)
    );
    iconRegistry.addSvgIcon(
      'assignement',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/assignement.svg`)
    );
    iconRegistry.addSvgIcon(
      'time',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/time.svg`)
    );
    iconRegistry.addSvgIcon(
      'task-notes',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/task_notes.svg`)
    );
    iconRegistry.addSvgIcon(
      'white-list',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/white_list.svg`)
    );
    iconRegistry.addSvgIcon(
      'problems',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/problems.svg`)
    );
    iconRegistry.addSvgIcon(
      'organizational-chart',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/organizational_chart.svg`)
    );
    iconRegistry.addSvgIcon(
      'solution',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/solution.svg`)
    );
    iconRegistry.addSvgIcon(
      'delete',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/delete.svg`)
    );
    iconRegistry.addSvgIcon(
      'external-link',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/external_link.svg`)
    );
    iconRegistry.addSvgIcon(
      'record',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/record.svg`)
    );  
    iconRegistry.addSvgIcon(
      'flash',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/flash.svg`)
    );  
    iconRegistry.addSvgIcon(
      'palette',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/palette.svg`)
    );
    iconRegistry.addSvgIcon(
      'document',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/document.svg`)
    );
    iconRegistry.addSvgIcon(
      'treasure-chest',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/treasure_chest.svg`)
    );    
    iconRegistry.addSvgIcon(
      'copy',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/copy.svg`)
    );    
    iconRegistry.addSvgIcon(
      'garbage-can',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/garbage_can.svg`)
    );    
    iconRegistry.addSvgIcon(
      'cross',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/cross.svg`)
    );    
    iconRegistry.addSvgIcon(
      'lock-closed',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/lock_closed.svg`)
    );        
    iconRegistry.addSvgIcon(
      'arrow-left',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/arrow_left.svg`)
    );
    iconRegistry.addSvgIcon(
      'wrench',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/wrench.svg`)
    );
    iconRegistry.addSvgIcon(
      'pencil',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/pencil.svg`)
    );
    iconRegistry.addSvgIcon(
      'world',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/world.svg`)
    );
    iconRegistry.addSvgIcon(
      'disconnect',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/disconnect.svg`)
    );
    iconRegistry.addSvgIcon(
      'allow_list2',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/allow_list2.svg`)
    );
    iconRegistry.addSvgIcon(
      'file',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/file.svg`)
    );
    iconRegistry.addSvgIcon(
      'equation',
      sanitizer.bypassSecurityTrustResourceUrl(`../../../${environment.assetsUrl}/icons/equation.svg`)
    );
  }
  
}
