import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DomSanitizer } from "@angular/platform-browser";
import { MatIconRegistry } from '@angular/material/icon';

@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class IconsModule { 

  constructor (
    iconRegistry: MatIconRegistry,
    sanitizer: DomSanitizer,
  ) {
    iconRegistry.addSvgIcon(
      "vertical-menu",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/vertical_menu.svg")
    );
    iconRegistry.addSvgIcon(
      "menu",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/menu.svg")
    );
    iconRegistry.addSvgIcon(
      "download",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/download.svg")
    );
    iconRegistry.addSvgIcon(
      "reload",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/reload.svg")
    );
    iconRegistry.addSvgIcon(
      "attachment",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/attachment.svg")
    );
    iconRegistry.addSvgIcon(
      "save",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/save.svg")
    );
    iconRegistry.addSvgIcon(
      "cancel",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/cancel.svg")
    );
    iconRegistry.addSvgIcon(
      "checklist",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/checklist.svg")
    );
    iconRegistry.addSvgIcon(
      "support",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/support.svg")
    );
    iconRegistry.addSvgIcon(
      "checklist-header",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/checklist_header.svg")
    );
    iconRegistry.addSvgIcon(
      "small-locked",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/small_locked.svg")
    );
    iconRegistry.addSvgIcon(
      "arrow-up",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/arrow_up.svg")
    );
    iconRegistry.addSvgIcon(
      "arrow-down",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/arrow_down.svg")
    );
    iconRegistry.addSvgIcon(
      "check",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/check.svg")
    );
    iconRegistry.addSvgIcon(
      "warn-line",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/warn_line.svg")
    );  
    iconRegistry.addSvgIcon(
      "warn-fill",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/warn_fill.svg")
    );
    iconRegistry.addSvgIcon(
      "block",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/block.svg")
    );
    iconRegistry.addSvgIcon(
      "attachment-file",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/attachment_file.svg")
    );
    iconRegistry.addSvgIcon(
      "more_info",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/more_info.svg")
    );
    iconRegistry.addSvgIcon(
      "event",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/event.svg")
    );
    iconRegistry.addSvgIcon(
      "man",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/man.svg")
    );
    iconRegistry.addSvgIcon(
      "briefcase",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/briefcase.svg")
    );
    iconRegistry.addSvgIcon(
      "gear",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/gear.svg")
    );
    iconRegistry.addSvgIcon(
      "industry",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/industry.svg")
    );
    iconRegistry.addSvgIcon(
      "country",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/country.svg")
    );
    iconRegistry.addSvgIcon(
      "company",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/company.svg")
    );
    iconRegistry.addSvgIcon(
      "priority",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/priority.svg")
    );
    iconRegistry.addSvgIcon(
      "assignement",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/assignement.svg")
    );
    iconRegistry.addSvgIcon(
      "time",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/time.svg")
    );
    iconRegistry.addSvgIcon(
      "task-notes",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/task_notes.svg")
    );
    iconRegistry.addSvgIcon(
      "white-list",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/white_list.svg")
    );
    iconRegistry.addSvgIcon(
      "problems",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/problems.svg")
    );
    iconRegistry.addSvgIcon(
      "organizational-chart",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/organizational_chart.svg")
    );
    iconRegistry.addSvgIcon(
      "solution",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/solution.svg")
    );
    iconRegistry.addSvgIcon(
      "delete",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/delete.svg")
    );
    iconRegistry.addSvgIcon(
      "external-link",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/external_link.svg")
    );
    iconRegistry.addSvgIcon(
      "record",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/record.svg")
    );  
    iconRegistry.addSvgIcon(
      "flash",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/flash.svg")
    );  
    iconRegistry.addSvgIcon(
      "palette",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/palette.svg")
    );
    iconRegistry.addSvgIcon(
      "document",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/document.svg")
    );
    iconRegistry.addSvgIcon(
      "treasure-chest",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/treasure_chest.svg")
    );    
    iconRegistry.addSvgIcon(
      "copy",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/copy.svg")
    );    
    iconRegistry.addSvgIcon(
      "garbage-can",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/garbage_can.svg")
    );    
    iconRegistry.addSvgIcon(
      "cross",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/cross.svg")
    );    
    iconRegistry.addSvgIcon(
      "lock-closed",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/lock_closed.svg")
    );        
    iconRegistry.addSvgIcon(
      "arrow-left",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/arrow_left.svg")
    );
    iconRegistry.addSvgIcon(
      "wrench",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/wrench.svg")
    );
    iconRegistry.addSvgIcon(
      "pencil",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/pencil.svg")
    );
    iconRegistry.addSvgIcon(
      "world",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/world.svg")
    );
    iconRegistry.addSvgIcon(
      "disconnect",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/disconnect.svg")
    );
  }
  
}
