import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DomSanitizer } from "@angular/platform-browser";
import { MatIconRegistry } from '@angular/material/icon';

@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class IconsModule { 

  constructor (
    iconRegistry: MatIconRegistry,
    sanitizer: DomSanitizer,
  ) {
    iconRegistry.addSvgIcon(
      "vertical-menu",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/vertical_menu.svg")
    );
    iconRegistry.addSvgIcon(
      "menu",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/menu.svg")
    );
    iconRegistry.addSvgIcon(
      "download",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/download.svg")
    );
    iconRegistry.addSvgIcon(
      "reload",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/reload.svg")
    );
    iconRegistry.addSvgIcon(
      "attachment",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/attachment.svg")
    );
    iconRegistry.addSvgIcon(
      "save",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/save.svg")
    );
    iconRegistry.addSvgIcon(
      "cancel",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/cancel.svg")
    );
    iconRegistry.addSvgIcon(
      "checklist",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/checklist.svg")
    );
    iconRegistry.addSvgIcon(
      "support",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/support.svg")
    );
    iconRegistry.addSvgIcon(
      "checklist-header",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/checklist_header.svg")
    );
    iconRegistry.addSvgIcon(
      "small-locked",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/small_locked.svg")
    );
    iconRegistry.addSvgIcon(
      "arrow-up",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/arrow_up.svg")
    );
    iconRegistry.addSvgIcon(
      "arrow-down",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/arrow_down.svg")
    );
    iconRegistry.addSvgIcon(
      "check",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/check.svg")
    );
    iconRegistry.addSvgIcon(
      "warn_line",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/warn_line.svg")
    );  
    iconRegistry.addSvgIcon(
      "warn_fill",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/warn_fill.svg")
    );
    iconRegistry.addSvgIcon(
      "block",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/block.svg")
    );
    iconRegistry.addSvgIcon(
      "attachment_file",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/attachment_file.svg")
    );
    iconRegistry.addSvgIcon(
      "more_info",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/more_info.svg")
    );
    iconRegistry.addSvgIcon(
      "event",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/event.svg")
    );
    iconRegistry.addSvgIcon(
      "man",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/man.svg")
    );
    iconRegistry.addSvgIcon(
      "briefcase",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/briefcase.svg")
    );
    iconRegistry.addSvgIcon(
      "gear",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/gear.svg")
    );
    iconRegistry.addSvgIcon(
      "industry",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/industry.svg")
    );
    iconRegistry.addSvgIcon(
      "country",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/country.svg")
    );
    iconRegistry.addSvgIcon(
      "company",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/company.svg")
    );
    iconRegistry.addSvgIcon(
      "priority",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/priority.svg")
    );
    iconRegistry.addSvgIcon(
      "assignement",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/assignement.svg")
    );
    iconRegistry.addSvgIcon(
      "time",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/time.svg")
    );
    iconRegistry.addSvgIcon(
      "task_notes",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/task_notes.svg")
    );
    iconRegistry.addSvgIcon(
      "white_list",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/white_list.svg")
    );
    iconRegistry.addSvgIcon(
      "problems",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/problems.svg")
    );
    iconRegistry.addSvgIcon(
      "organizational_chart",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/organizational_chart.svg")
    );
    iconRegistry.addSvgIcon(
      "solution",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/solution.svg")
    );
    iconRegistry.addSvgIcon(
      "delete",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/delete.svg")
    );
    iconRegistry.addSvgIcon(
      "external_link",
      sanitizer.bypassSecurityTrustResourceUrl("../../../assets/icons/external_link.svg")
    );    
  }
}
